### ISSUE TITLE
Node SASS compiling error

### ISSUE THREAD

**Issue by fortael** [drewjbartlett/vue-switches#10]
I'm using laravel mix for building

```
95% emitting                                                                           

 ERROR  Failed to compile with 1 errors                                                                                                                                                                                    07:58:56

 error  in ./~/vue-switches/switches.vue

Module build failed: Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.5.2
    at module.exports (/Users/fortael/PhpstormProjects/many-templates/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/fortael/PhpstormProjects/many-templates/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/fortael/PhpstormProjects/many-templates/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at loadLoader (/Users/fortael/PhpstormProjects/many-templates/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/Users/fortael/PhpstormProjects/many-templates/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/fortael/PhpstormProjects/many-templates/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/fortael/PhpstormProjects/many-templates/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/fortael/PhpstormProjects/many-templates/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/fortael/PhpstormProjects/many-templates/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/Users/fortael/PhpstormProjects/many-templates/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /Users/fortael/PhpstormProjects/many-templates/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/Users/fortael/PhpstormProjects/many-templates/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/Users/fortael/PhpstormProjects/many-templates/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/fortael/PhpstormProjects/many-templates/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/Users/fortael/PhpstormProjects/many-templates/node_modules/webpack/lib/NormalModule.js:179:3)
    at NormalModule.build (/Users/fortael/PhpstormProjects/many-templates/node_modules/webpack/lib/NormalModule.js:268:15)

 @ ./~/vue-style-loader!./~/css-loader!./~/vue-loader/lib/style-compiler?{"id":"data-v-6d1dbd09","scoped":false,"hasInlineConfig":true}!./~/sass-loader/lib/loader.js!./~/vue-loader/lib/selector.js?type=styles&index=0!./~/vue-switches/switches.vue 4:14-256
 @ ./~/vue-switches/switches.vue
 @ ./dist/_admin.js
 @ multi ./dist/_admin.js

```

**Comment by drewjbartlett** [comment]
This shouldn't be an issue anymore. I just updated to v2 that no longer has node-sass as dependency. The component now includes a css file.
