### ISSUE TITLE
Failed to load switches.vue

### ISSUE THREAD

**Issue by imkimchi** [drewjbartlett/vue-switches#17]
It keeps failing to load switches component due to syntax error, no idea why this is not working.

```
{ /node_modules/vue-switches/src/switches.vue:1
(function (exports, require, module, __filename, __dirname) { <template>
                                                              ^

SyntaxError: Unexpected token <
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at r (/home/server2/1MM-apps/node_modules/vue-server-renderer/build.js:8330:16)
    at Object.<anonymous> (server-bundle.js:3677:18)
    at __webpack_require__ (webpack:/webpack/bootstrap 8f00aa7521ecf95414fa:25:0)
    at Object.<anonymous> (components/settings/Countdown.vue?32d3:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 8f00aa7521ecf95414fa:25:0)
    at Object.<anonymous> (components/settings/Countdown.vue:1:0) statusCode: 500, name: 'SyntaxError' }
```

**Comment by JeffVa1** [comment]
No worky.

**Comment by romainframe** [comment]
Adding this to NuxtJS config build did the trick for me

`transpile: [/^vue-switches($|\/)/]`
